//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2015-10-25 00:23:55
namespace DsbForsinket.MobileService.DsbLabs
{
    
    /// <summary>
    /// There are no comments for DSBLabsStationService in the schema.
    /// </summary>
    public partial class DSBLabsStationService : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DSBLabsStationService object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DSBLabsStationService(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "ITogLogic.Support", "DsbForsinket.MobileService.DsbLabs.ITogLogic.Support");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "ITogLogic.Model", "DsbForsinket.MobileService.DsbLabs");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("DsbForsinket.MobileService.DsbLabs.ITogLogic.Support", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ITogLogic.Support.", clientType.Name);
            }
            if (clientType.Namespace.Equals("DsbForsinket.MobileService.DsbLabs", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ITogLogic.Model.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Station in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Station> Station
        {
            get
            {
                if ((this._Station == null))
                {
                    this._Station = base.CreateQuery<Station>("Station");
                }
                return this._Station;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Station> _Station;
        /// <summary>
        /// There are no comments for Queue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Queue> Queue
        {
            get
            {
                if ((this._Queue == null))
                {
                    this._Queue = base.CreateQuery<Queue>("Queue");
                }
                return this._Queue;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Queue> _Queue;
        /// <summary>
        /// There are no comments for Station in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStation(Station station)
        {
            base.AddObject("Station", station);
        }
        /// <summary>
        /// There are no comments for Queue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToQueue(Queue queue)
        {
            base.AddObject("Queue", queue);
        }
    }
    /// <summary>
    /// There are no comments for ITogLogic.Model.Station in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UIC
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("UIC")]
    public partial class Station
    {
        /// <summary>
        /// Create a new Station object.
        /// </summary>
        /// <param name="uIC">Initial value of UIC.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Station CreateStation(string uIC)
        {
            Station station = new Station();
            station.UIC = uIC;
            return station;
        }
        /// <summary>
        /// There are no comments for Property Abbreviation in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Abbreviation
        {
            get
            {
                return this._Abbreviation;
            }
            set
            {
                this.OnAbbreviationChanging(value);
                this._Abbreviation = value;
                this.OnAbbreviationChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Abbreviation;
        partial void OnAbbreviationChanging(string value);
        partial void OnAbbreviationChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property UIC in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UIC
        {
            get
            {
                return this._UIC;
            }
            set
            {
                this.OnUICChanging(value);
                this._UIC = value;
                this.OnUICChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UIC;
        partial void OnUICChanging(string value);
        partial void OnUICChanged();
        /// <summary>
        /// There are no comments for Property CountryCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CountryCode
        {
            get
            {
                return this._CountryCode;
            }
            set
            {
                this.OnCountryCodeChanging(value);
                this._CountryCode = value;
                this.OnCountryCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CountryCode;
        partial void OnCountryCodeChanging(string value);
        partial void OnCountryCodeChanged();
        /// <summary>
        /// There are no comments for Property CountryName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CountryName
        {
            get
            {
                return this._CountryName;
            }
            set
            {
                this.OnCountryNameChanging(value);
                this._CountryName = value;
                this.OnCountryNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CountryName;
        partial void OnCountryNameChanging(string value);
        partial void OnCountryNameChanged();
    }
    /// <summary>
    /// There are no comments for ITogLogic.Model.Queue in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Queue
    {
        /// <summary>
        /// Create a new Queue object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="generated">Initial value of Generated.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Queue CreateQueue(string ID, global::System.DateTime generated)
        {
            Queue queue = new Queue();
            queue.ID = ID;
            queue.Generated = generated;
            return queue;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ID;
        partial void OnIDChanging(string value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property StationUic in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string StationUic
        {
            get
            {
                return this._StationUic;
            }
            set
            {
                this.OnStationUicChanging(value);
                this._StationUic = value;
                this.OnStationUicChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _StationUic;
        partial void OnStationUicChanging(string value);
        partial void OnStationUicChanged();
        /// <summary>
        /// There are no comments for Property TrainType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TrainType
        {
            get
            {
                return this._TrainType;
            }
            set
            {
                this.OnTrainTypeChanging(value);
                this._TrainType = value;
                this.OnTrainTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TrainType;
        partial void OnTrainTypeChanging(string value);
        partial void OnTrainTypeChanged();
        /// <summary>
        /// There are no comments for Property DestinationName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DestinationName
        {
            get
            {
                return this._DestinationName;
            }
            set
            {
                this.OnDestinationNameChanging(value);
                this._DestinationName = value;
                this.OnDestinationNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DestinationName;
        partial void OnDestinationNameChanging(string value);
        partial void OnDestinationNameChanged();
        /// <summary>
        /// There are no comments for Property DestinationID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> DestinationID
        {
            get
            {
                return this._DestinationID;
            }
            set
            {
                this.OnDestinationIDChanging(value);
                this._DestinationID = value;
                this.OnDestinationIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _DestinationID;
        partial void OnDestinationIDChanging(global::System.Nullable<int> value);
        partial void OnDestinationIDChanged();
        /// <summary>
        /// There are no comments for Property Track in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Track
        {
            get
            {
                return this._Track;
            }
            set
            {
                this.OnTrackChanging(value);
                this._Track = value;
                this.OnTrackChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Track;
        partial void OnTrackChanging(string value);
        partial void OnTrackChanged();
        /// <summary>
        /// There are no comments for Property Generated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Generated
        {
            get
            {
                return this._Generated;
            }
            set
            {
                this.OnGeneratedChanging(value);
                this._Generated = value;
                this.OnGeneratedChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Generated;
        partial void OnGeneratedChanging(global::System.DateTime value);
        partial void OnGeneratedChanged();
        /// <summary>
        /// There are no comments for Property TrainNumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TrainNumber
        {
            get
            {
                return this._TrainNumber;
            }
            set
            {
                this.OnTrainNumberChanging(value);
                this._TrainNumber = value;
                this.OnTrainNumberChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TrainNumber;
        partial void OnTrainNumberChanging(string value);
        partial void OnTrainNumberChanged();
        /// <summary>
        /// There are no comments for Property DestinationCountryCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DestinationCountryCode
        {
            get
            {
                return this._DestinationCountryCode;
            }
            set
            {
                this.OnDestinationCountryCodeChanging(value);
                this._DestinationCountryCode = value;
                this.OnDestinationCountryCodeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DestinationCountryCode;
        partial void OnDestinationCountryCodeChanging(string value);
        partial void OnDestinationCountryCodeChanged();
        /// <summary>
        /// There are no comments for Property ScheduledArrival in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> ScheduledArrival
        {
            get
            {
                return this._ScheduledArrival;
            }
            set
            {
                this.OnScheduledArrivalChanging(value);
                this._ScheduledArrival = value;
                this.OnScheduledArrivalChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _ScheduledArrival;
        partial void OnScheduledArrivalChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnScheduledArrivalChanged();
        /// <summary>
        /// There are no comments for Property ScheduledDeparture in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> ScheduledDeparture
        {
            get
            {
                return this._ScheduledDeparture;
            }
            set
            {
                this.OnScheduledDepartureChanging(value);
                this._ScheduledDeparture = value;
                this.OnScheduledDepartureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _ScheduledDeparture;
        partial void OnScheduledDepartureChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnScheduledDepartureChanged();
        /// <summary>
        /// There are no comments for Property ArrivalDelay in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> ArrivalDelay
        {
            get
            {
                return this._ArrivalDelay;
            }
            set
            {
                this.OnArrivalDelayChanging(value);
                this._ArrivalDelay = value;
                this.OnArrivalDelayChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _ArrivalDelay;
        partial void OnArrivalDelayChanging(global::System.Nullable<long> value);
        partial void OnArrivalDelayChanged();
        /// <summary>
        /// There are no comments for Property DepartureDelay in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> DepartureDelay
        {
            get
            {
                return this._DepartureDelay;
            }
            set
            {
                this.OnDepartureDelayChanging(value);
                this._DepartureDelay = value;
                this.OnDepartureDelayChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _DepartureDelay;
        partial void OnDepartureDelayChanging(global::System.Nullable<long> value);
        partial void OnDepartureDelayChanged();
        /// <summary>
        /// There are no comments for Property Cancelled in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Cancelled
        {
            get
            {
                return this._Cancelled;
            }
            set
            {
                this.OnCancelledChanging(value);
                this._Cancelled = value;
                this.OnCancelledChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Cancelled;
        partial void OnCancelledChanging(global::System.Nullable<bool> value);
        partial void OnCancelledChanged();
        /// <summary>
        /// There are no comments for Property Line in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Line
        {
            get
            {
                return this._Line;
            }
            set
            {
                this.OnLineChanging(value);
                this._Line = value;
                this.OnLineChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Line;
        partial void OnLineChanging(string value);
        partial void OnLineChanged();
        /// <summary>
        /// There are no comments for Property Direction in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Direction
        {
            get
            {
                return this._Direction;
            }
            set
            {
                this.OnDirectionChanging(value);
                this._Direction = value;
                this.OnDirectionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Direction;
        partial void OnDirectionChanging(string value);
        partial void OnDirectionChanged();
        /// <summary>
        /// There are no comments for Property MinutesToDeparture in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string MinutesToDeparture
        {
            get
            {
                return this._MinutesToDeparture;
            }
            set
            {
                this.OnMinutesToDepartureChanging(value);
                this._MinutesToDeparture = value;
                this.OnMinutesToDepartureChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _MinutesToDeparture;
        partial void OnMinutesToDepartureChanging(string value);
        partial void OnMinutesToDepartureChanged();
    }
}
// Original file name:
// Generation date: 2015-10-25 00:23:55
namespace DsbForsinket.MobileService.DsbLabs.ITogLogic.Support
{
    
    /// <summary>
    /// There are no comments for ITogLogic.Support.QueueTestBuilder in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class QueueTestBuilder : DsbForsinket.MobileService.DsbLabs.Queue
    {
        /// <summary>
        /// Create a new QueueTestBuilder object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="generated">Initial value of Generated.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static QueueTestBuilder CreateQueueTestBuilder(string ID, global::System.DateTime generated)
        {
            QueueTestBuilder queueTestBuilder = new QueueTestBuilder();
            queueTestBuilder.ID = ID;
            queueTestBuilder.Generated = generated;
            return queueTestBuilder;
        }
    }
}
